Repository Quaran-Team/server-Amazin, pull requests merged in 2020-08, with the labels that each got.

#74 get by id route added
  api/src/main/java/com/talentpath/amazin/api/customerImage/CustomerImageResource.java
  api/src/main/java/com/talentpath/amazin/api/customerWhoBoughtAlso/CustomerWhoBoughtAlsoResource.java
Labels: bug, enhancement

#75 Feature/ratingsummarystars
  api/src/main/java/com/talentpath/amazin/api/summaryratingstars/SummaryStarRatingsController.java
Labels: bug

#79 Chore/readme
  README.md
  git pics/items.JPG
  git pics/totalstars.JPG
Labels: chore, documentation

#84 Readme final
  README.md
  git pics/tests.JPG
Labels: documentation
